let recipes = [
    {id: 1,
    title: "Dish 1",
    intro: "this is dish 1",
    ingr: ["½ cup chopped onion",
        "½ cup chopped green bell pepper",
        "2 (10 ounce) packages mixed salad greens",
        "4 thinly sliced chicken deli meat, chopped",
        "1 tomato, chopped",
        "¼ teaspoon onion powder",
        "3 dashes garlic powder",
        "2 pinches salt and ground black pepper to taste",
        "3 tablespoons balsamic vinaigrette salad dressing "],
    instr: ["Place onion and bell pepper in a microwave-safe bowl; heat in microwave on high until soft, about 1 to 2 minutes. Set aside to cool.",
            "Combine onion, bell pepper, salad greens, deli meat, and tomato in a large salad bowl. Sprinkle with onion powder, garlic powder, salt, and black pepper; toss well to mix. ", 
            "Pour on salad dressing; toss well and serve. "],
    img: "img/gallery/04.jpg",
    calo: 29,
    nutri: "calo:, fatL, cab:, sugar"},
    
    {id: 2,
    title: "Dish 2",
    intro: "this is dish 1",
    ingr: [ "2½ cups spelt flour, plus extra for rolling",
            "pinch of  salt",
            "2 tablespoon of  sachet dried yeast",
            "½ teaspoon sugar",
            "1 cup warm water",
            "1 tablespoon olive oil",
            "9oz fresh beetroot, finely grated and excess moisture squeezed using paper towel",
            "spray oil",
            "½ cup no-added-salt tomato paste",
            "3 cups sliced button mushrooms",
            "7oz cherry tomatoes, halved",
            "1 eggplant, thinly sliced into small pieces",
            "¹/³ cup pitted kalamata olives, drained",
            "¾ cup grated mozzarella",
            "2 cups baby rocket, to serve"],
    instr: ["In a medium bowl, combine flour and salt. Make a well in the centre. add yeast and sugar. Pour in water and oil and mix gently. Add beetroot, and continue to mix until dough sticks together.",
            "lightly flour kitchen counter, place dough and knead for 3–4 minutes, or until smooth.",
            "Lightly spray a clean bowl with oil. Place dough in bowl and cover with plastic wrap and a tea towel. Set aside in a warm place for 30–40 minutes, or until dough has doubled in size.",
            "Preheat oven to 410°F. lightly grease two large pizza trays. Divide dough in half. Roll out each piece of dough until almost large enough to cover pizza tray. Lift dough on to pizza tray, and press to edges.",
            "Spread tomato paste over both pizzas, in equal portions. Top with mushrooms, tomatoes, eggplant and olives. Scatter over cheese and bake for 20–25 minutes, or until golden. Cut pizza into wedges, top with rocket and serve."],
    calo: 32,
    nutri: "calo:, fatL, cab:, sugar"},

    {id: 3,
    title: "Dish 3",
    intro: "this is dish 1",
    ingr: [ "8-10 corn tortillas",
            "1 piece fresh salmon (about 1/2 pound)",
            "1 teaspoon olive oil",
            "Garlic powder to taste",
            "Ground cumin to taste",
            "Chili powder (optional) to taste",
            "Salt & pepper to taste",
            "Sauce: 1 cup plain Greek yogurt, Juice from 1/2 lime, 1 clove garlic minced, Handful fresh cilantro chopped",
            "Toppings: 1 avocado diced, 2 small lettuce bulb shredded, Lime wedges to taste" ],
    instr: ["Preheat oven to 375F. Move the rack to the middle position",
            "Line a baking sheet with foil. Wrap the tortillas in foil and put them in the oven right away.",
            "Place a piece of salmon on the baking sheet and coat it with olive oil.",
            "Gently sprinkle with garlic powder, ground cumin, chili powder, and salt & pepper.",
            "Cook in oven for 10-15 minutes or until it flakes easily with a fork.",
            "Meanwhile, combine the sauce ingredients. Set aside. Prepare the avocado and lettuce.",
            "When the salmon is done, roughly cut it into bite-size pieces using a fork.",
            "Assemble tacos immediately. Serve with extra lime if desired."],
    calo: 34,
    nutri: "calo:, fatL, cab:, sugar"}, 

    {id: 4,
    title: "Dish 1",
    intro: "this is dish 1",
    ingr: ["3 large tomatoes, cut into wedges",
           "4 cloves garlic, unpeeled",
           "2 tablespoons olive oil",
           "1/4 teaspoon salt",
           "Freshly ground black pepper",
           "1(15 ounce) can white beans",
           "1/2 pound penne pasta",
           "1/4 cup fresh basil leaves, torn",
           "2 tablespoons freshly grated Parmesan"],
    instr: ["b1", "b2", "b3"],
    img: "img/gallery/04.jpg",
    calo: 29,
    nutri: "calo:, fatL, cab:, sugar"},
    
    {id: 5,
    title: "Dish 2",
    intro: "this is dish 1",
    ingr: ["b1", "b2", "b3"],
    instr: ["b1", "b2", "b3"],
    calo: 32,
    nutri: "calo:, fatL, cab:, sugar"},

    {id: 6,
    title: "Dish 3",
    intro: "this is dish 1",
    ingr: ["b1", "b2", "b3"],
    instr: ["b1", "b2", "b3"],
    calo: 34,
    nutri: "calo:, fatL, cab:, sugar"}
]