let recipes = [
    //8 first recipe follows the orser of the index.html
    {id: 1,
    title: "Mixed Salad",
    ingr_search:["onion", "green bell pepper","chicken","tomato","garlic"],
    ingr: ["½ cup chopped onion",
        "½ cup chopped green bell pepper",
        "2 (10 ounce) packages mixed salad greens",
        "4 thinly sliced chicken deli meat, chopped",
        "1 tomato, chopped",
        "¼ teaspoon onion powder",
        "3 dashes garlic powder",
        "2 pinches salt and ground black pepper to taste",
        "3 tablespoons balsamic vinaigrette salad dressingcal "],
    instr: ["Place onion and bell pepper in a microwave-safe bowl; heat in microwave on high until soft, about 1 to 2 minutes. Set aside to cool.",
            "Combine onion, bell pepper, salad greens, deli meat, and tomato in a large salad bowl. Sprinkle with onion powder, garlic powder, salt, and black pepper; toss well to mix. ", 
            "Pour on salad dressing; toss well and serve."],
    img: "img/gallery/01.jpg",
    calo: 190,
    nutri: "Calories: 190cal, Fat: 12g, Cabohydrate: 8g, Protein: 12g, Sugar: 0g"},
    
    {id: 2,
    title: "Vegetarian Pizza",
    ingr_search:["flour", "vegetable","cheese","tomato","beetroot", "baby rocket"],
    ingr: [ "2½ cups spelt flour, plus extra for rolling",
            "pinch of  salt",
            "2 tablespoon of  sachet dried yeast",
            "½ teaspoon sugar",
            "1 cup warm water",
            "1 tablespoon olive oil",
            "9oz fresh beetroot, finely grated and excess moisture squeezed using paper towel",
            "spray oil",
            "½ cup no-added-salt tomato paste",
            "3 cups sliced button mushrooms",
            "7oz cherry tomatoes, halved",
            "1 eggplant, thinly sliced into small pieces",
            "¹/³ cup pitted kalamata olives, drained",
            "¾ cup grated mozzarella",
            "2 cups baby rocket, to serve"],
    instr: ["In a medium bowl, combine flour and salt. Make a well in the centre. add yeast and sugar.",
            "Pour in water and oil and mix gently. ",
            "Add beetroot, and continue to mix until dough sticks together.",
            "lightly flour kitchen counter, place dough and knead for 3–4 minutes, or until smooth.",
            "Lightly spray a clean bowl with oil. ", 
            "Place dough in bowl and cover with plastic wrap and a tea towel.",
            "Set aside in a warm place for 30–40 minutes, or until dough has doubled in size.",
            "Preheat oven to 410°F. lightly grease two large pizza trays.", 
            "Divide dough in half. Roll out each piece of dough until almost large enough to cover pizza tray.",
            "Lift dough on to pizza tray, and press to edges.",
            "Spread tomato paste over both pizzas, in equal portions. Top with mushrooms, tomatoes, eggplant and olives. Scatter over cheese and bake for 20–25 minutes, or until golden. Cut pizza into wedges, top with rocket and serve."],
    img: "img/gallery/02.jpg",
    calo: 440,
    nutri: "Calories: 440cal, Fat: 20.1g, Cabohydrate: 44.9g, Protein: 12g, Sugar: 6g"},

    {id: 3,
    title: "Salmon taco",
    ingr_search:["corn", "tortillas","salmon","tomato","yogurt", "avocado", "lettuce"],
    ingr: [ "8-10 corn tortillas",
            "1 piece fresh salmon (about 1/2 pound)",
            "1 teaspoon olive oil",
            "Garlic powder to taste",
            "Ground cumin to taste",
            "Chili powder (optional) to taste",
            "Salt & pepper to taste",
            "Sauce: 1 cup plain Greek yogurt, Juice from 1/2 lime, 1 clove garlic minced, Handful fresh cilantro chopped",
            "Toppings: 1 avocado diced, 2 small lettuce bulb shredded, Lime wedges to taste" ],
    instr: ["Preheat oven to 375F. Move the rack to the middle position",
            "Line a baking sheet with foil. Wrap the tortillas in foil and put them in the oven right away.",
            "Place a piece of salmon on the baking sheet and coat it with olive oil.",
            "Gently sprinkle with garlic powder, ground cumin, chili powder, and salt & pepper.",
            "Cook in oven for 10-15 minutes or until it flakes easily with a fork.",
            "Meanwhile, combine the sauce ingredients. Set aside. Prepare the avocado and lettuce.",
            "When the salmon is done, roughly cut it into bite-size pieces using a fork.",
            "Assemble tacos immediately. Serve with extra lime if desired."],
    img: "img/gallery/03.jpg",
    calo: 34,
    nutri: "Calories: 414cal, Fat: 19g, Cabohydrate: 26g, Protein: 22g, Sugar: 3g"}, 

    {id: 4,
    title: "Vegetarian Pasta",
    ingr_search:["pasta", "tomato","beans","cheese"],
    ingr: ["3 large tomatoes, cut into wedges",
           "4 cloves garlic, unpeeled",
           "2 tablespoons olive oil",
           "1/4 teaspoon salt",
           "Freshly ground black pepper",
           "1(15 ounce) can white beans",
           "1/2 pound penne pasta",
           "1/4 cup fresh basil leaves, torn",
           "2 tablespoons freshly grated Parmesan"],
    instr: ["Preheat the oven to 450 degrees Farenheit.",
            "Slice each tomato into 8 wedges and discard the seeds. ",
            "Put the tomato wedges and garlic into a 9 x 13-inch roasting pan. ",
            "Drizzle with 1 tablespoon of olive oil and sprinkle with salt and a few turns of pepper.",
            "Roast in the oven, uncovered, for 40 minutes.",
            "Drain the beans into a large colander in the sink.",
            "Cook the pasta according to the directions on the package.", 
            "Drain the pasta into the colander containing the beans, so the hot pasta water will warm the beans.",
            "Return drained pasta and beans to the pasta pot.",
            "When the tomatoes are done, pick out the garlic cloves, squeeze the garlic out of the skin into a small bowl and mash with a fork.",
            "Pour the roasted tomatoes into the pasta pot, add the garlic, the remaining 1 tablespoon of olive oil, the basil and additional salt and pepper, to taste.",
            "Toss to combine.",
            "Serve topped with the Parmesan." ],
    img: "img/gallery/04.jpg",
    calo: 592,
    nutri: "Calories: 592cal, Fat: 27g, Cabohydrate: 62g, Protein: 17g, Sugar: 2g"},

    {id: 5,
    title: "Healthy baked meatball",
    ingr_search:["beef", "onion","cheese"],
    ingr: ["1 pound lean ground beef",
           "1/2 cup onion finely chopped",
           "1/4 cup dried bread crumbs",
           "2 garlic cloves minced",
           "1 egg",
           "1/4 cup parmesan cheese finely grated",
           "3 Tbsp. ketchup",
           "1 tsp. salt",
           "1/4 tsp. pepper",
           "1 Tbsp. parsley minced (or about 1/2 Tbsp. dried)",],
    instr: ["Preheat oven to 400ºF. Spray a large cookie sheet with cooking spray.",
            "Mix together onion, bread crumbs, garlic, egg, cheese, ketchup, salt, pepper and parsley in a large mixing bowl.",
            "Add in ground beef and mix gently until combined. Do not overwork.", 
            "Form into 1-inch balls and place on prepared cookie sheet.",
            "Bake in preheated oven for 15-20 minutes, or until meatballs are browned and cooked through"],
    img: "img/gallery/05.jpg",
    calo: 400,
    nutri: "Calories: 400cal, Fat: 17g, Cabohydrate: 16g, Protein: 30g, Sugar: 0.5g"},


    //Delete intro item -> no need anymore
    {id: 6,
    title: "Fruit toast with zero-Calorie syrup",
    ingr_search:["bread", "fruit","cheese"],
    ingr: ["Slices of bread", "Fruit of your choice", "Cream cheese"],
    instr: ["Toast your bread on a hot pan or a toaster", 
            "Spread on a thin layer of cream cheese", 
            "Top with fruit and syrup"],
    img: "img/gallery/06.jpg",
    calo: 172,
    nutri: "Calories: 172cal, Fat: 10g, Cabohydrate: 13g, Protein: 7g, Sugar: 0g"},

    {id: 7,
    title: "Fruit Salad",
    ingr_search:["fruit", "yogurt","honey"],
    ingr: ["1 cup plain yogurt",
    "1/4 cup honey",
    "1/2 teaspoon",
    "1 orange",
    "1 cup fresh strawberries cut in half",
    "2 clementines or tangerines sliced",
    "1 mango sliced",
    "1 apple sliced",
    "1 banana sliced"],
    instr: ["Slice your fruit in thinslices", 
            "Sepreate segments of clementines", 
            "Juice the orange",
            "Making the sauce: combine the yogurt, honey in a small bowl; mix well and set aside",
            "Combine the fresh orange juice with all the fresh fruit",
            "Top with honey yogurt sauce"],
    img: "img/gallery/07.jpg",
    calo: 32,
    nutri: "Calories: 250cal, Fat: 2.7g, Cabohydrate: 57.4g, Protein: 4.2g, Sugar: 0g"},

    {id: 8,
    title: "Dish 3",
    ingr_search:["chicken", "cabbage"],
    ingr: ["10 ounces skinless chicken breast, ﬁnely chopped",
           "6 ounces medium yellow Napa cabbage (approximately ⅕ cabbage), shredded",
           "2 slices fresh ginger, ⅛ to ¼ inch thick, diced",
           "2 scallions, finely chopped",
           "1 teaspoon salt",
           "1½ teaspoons sugar",
           "1 tablespoon chicken powder",
           "2 scallions, finely chopped",
           "1 teaspoon salt",
           "1½ teaspoons sugar",
           "1 tablespoon chicken powder",
           "1/4 teaspoon ground white pepper",
           "1 teaspoon cornstarch",
           " 1 teaspoon toasted sesame oil",
           "20 Shanghai-style circular wrappers",
           "1/4 teaspoon ground white pepper",
           "1 teaspoon cornstarch",
           "1 teaspoon toasted sesame oil",
           "20 Shanghai-style circular wrappers"],
    instr: ["In a large bowl, mix together the chicken, cabbage, ginger, and scallions until the mixture resembles a fine paste. Add the salt, sugar, chicken powder, white pepper, cornstarch, and toasted sesame oil and continue to stir for 3 to 5 minutes, until well incorporated.", 
            "Dampen a towel under which to keep the rest of the dumpling wrappers while you work.", 
            "Prepare a parchment-lined baking sheet on which to store the already prepared dumplings.",
            "Place 1½ teaspoons of filling in the center of each dumpling wrapper. Fold the dumpling into a half-moon shape. Hold the dumpling, seam-side up, between your thumb and index finger. Use the index finger and thumb of your other hand to pinch a section of the dumpling edge and pull it toward the web of the holding hand to make a small pleat. Repeat around the edge of the dumpling until you have between 6 and 8 pleats.",
            "Steam the dumpling and serve"],
    img: "img/gallery/08.jpg",
    calo: 34,
    nutri: "Calories: 190cal, Fat: 2.1g, Cabohydrate: 24.2g, Protein: 17.8g, Sugar: 0g"},
    
    {id: 9,
    title: "Dish 2",
    intro: "this is dish 1",
    ingr: ["b1", "b2", "b3"],
    instr: ["b1", "b2", "b3"],
    calo: 32,
    nutri: "calo:, fatL, cab:, sugar"},

    {id: 10,
    title: "Dish 3",
    intro: "this is dish 1",
    ingr: ["b1", "b2", "b3"],
    instr: ["b1", "b2", "b3"],
    calo: 34,
    nutri: "calo:, fatL, cab:, sugar"}
]