let recipes = [
        //8 first recipe follows the orser of the index.html
        {id: 1,
        title: "Mixed Salad",
        intro: "Vegetables are rich sources of potassium, dietary fiber, folate, vitamin A, and vitamin C.",
        ingr_search:["onion", "green bell pepper","chicken","tomato","garlic"],
        ingr: ["½ cup chopped onion",
                "½ cup chopped green bell pepper",
                "2 (10 ounce) packages mixed salad greens",
                "4 thinly sliced chicken deli meat, chopped",
                "1 tomato, chopped",
                "¼ teaspoon onion powder",
                "3 dashes garlic powder",
                "2 pinches salt and ground black pepper to taste",
                "3 tablespoons balsamic vinaigrette salad dressingcal "],
        instr: ["Place onion and bell pepper in a microwave-safe bowl; heat in microwave on high until soft, about 1 to 2 minutes. Set aside to cool.",
                "Combine onion, bell pepper, salad greens, deli meat, and tomato in a large salad bowl. Sprinkle with onion powder, garlic powder, salt, and black pepper; toss well to mix. ", 
                "Pour on salad dressing; toss well and serve."],
        img: "img/gallery/mixed_salad.jpg",
        calo: 190,
        nutri: "Energy: 190kcal, Fat: 12g, Cabohydrate: 8g, Protein: 12g, Sugar: 0g"},
        
        {id: 2,
        title: "Vegetarian Pizza",
        intro: "The taste is similar to a regular one, but it is a healthier version.",
        ingr_search:["flour", "vegetable","cheese","tomato","beetroot", "baby rocket","sachet"],
        ingr: [ "2½ cups spelt flour, plus extra for rolling",
                "pinch of salt",
                "2 tablespoon of sachet dried yeast",
                "½ teaspoon sugar",
                "1 cup warm water",
                "1 tablespoon olive oil",
                "9oz fresh beetroot, finely grated and excess moisture squeezed using paper towel",
                "spray oil",
                "½ cup no-added-salt tomato paste",
                "3 cups sliced button mushrooms",
                "7oz cherry tomatoes, halved",
                "1 eggplant, thinly sliced into small pieces",
                "¹/³ cup pitted kalamata olives, drained",
                "¾ cup grated mozzarella",
                "2 cups baby rocket, to serve"],
        instr: ["In a medium bowl, combine flour and salt. Make a well in the centre. add yeast and sugar.",
                "Pour in water and oil and mix gently. ",
                "Add beetroot, and continue to mix until dough sticks together.",
                "lightly flour kitchen counter, place dough and knead for 3–4 minutes, or until smooth.",
                "Lightly spray a clean bowl with oil. ", 
                "Place dough in bowl and cover with plastic wrap and a tea towel.",
                "Set aside in a warm place for 30–40 minutes, or until dough has doubled in size.",
                "Preheat oven to 410°F. lightly grease two large pizza trays.", 
                "Divide dough in half. Roll out each piece of dough until almost large enough to cover pizza tray.",
                "Lift dough on to pizza tray, and press to edges.",
                "Spread tomato paste over both pizzas, in equal portions. Top with mushrooms, tomatoes, eggplant and olives. Scatter over cheese and bake for 20–25 minutes, or until golden. Cut pizza into wedges, top with rocket and serve."],
        img: "img/gallery/vegie_pizza.jpg",
        calo: 440,
        nutri: "Energy: 440kcal, Fat: 20.1g, Cabohydrate: 44.9g, Protein: 12g, Sugar: 6g"},

        {id: 3,
        title: "Salmon Taco",
        intro: "Give Mexican food lovers an entirely new experience.",
        ingr_search:["corn", "tortillas","salmon","tomato","yogurt", "avocado", "lettuce"],
        ingr: [ "8-10 corn tortillas",
                "1 piece fresh salmon (about 1/2 pound)",
                "1 teaspoon olive oil",
                "Garlic powder to taste",
                "Ground cumin to taste",
                "Chili powder (optional) to taste",
                "Salt & pepper to taste",
                "Sauce: 1 cup plain Greek yogurt, Juice from 1/2 lime, 1 clove garlic minced, Handful fresh cilantro chopped",
                "Toppings: 1 avocado diced, 2 small lettuce bulb shredded, Lime wedges to taste" ],
        instr: ["Preheat oven to 375F. Move the rack to the middle position",
                "Line a baking sheet with foil. Wrap the tortillas in foil and put them in the oven right away.",
                "Place a piece of salmon on the baking sheet and coat it with olive oil.",
                "Gently sprinkle with garlic powder, ground cumin, chili powder, and salt & pepper.",
                "Cook in oven for 10-15 minutes or until it flakes easily with a fork.",
                "Meanwhile, combine the sauce ingredients. Set aside. Prepare the avocado and lettuce.",
                "When the salmon is done, roughly cut it into bite-size pieces using a fork.",
                "Assemble tacos immediately. Serve with extra lime if desired."],
        img: "img/gallery/salmon_taco.jpg",
        calo: 414,
        nutri: "Energy: 414kcal, Fat: 19g, Cabohydrate: 26g, Protein: 22g, Sugar: 3g"}, 

        {id: 4,
        title: "Vegetarian Pasta",
        intro: "Maintain the original taste while cutting calories.",
        ingr_search:["pasta", "tomato","bean","cheese","basil","parmesan","cheese","olive"],
        ingr: ["3 large tomatoes, cut into wedges",
                "4 cloves garlic, unpeeled",
                "2 tablespoons olive oil",
                "1/4 teaspoon salt",
                "Freshly ground black pepper",
                "1(15 ounce) can white beans",
                "1/2 pound penne pasta",
                "1/4 cup fresh basil leaves, torn",
                "2 tablespoons freshly grated Parmesan"],
        instr: ["Preheat the oven to 450 degrees Farenheit.",
                "Slice each tomato into 8 wedges and discard the seeds. ",
                "Put the tomato wedges and garlic into a 9 x 13-inch roasting pan. ",
                "Drizzle with 1 tablespoon of olive oil and sprinkle with salt and a few turns of pepper.",
                "Roast in the oven, uncovered, for 40 minutes.",
                "Drain the beans into a large colander in the sink.",
                "Cook the pasta according to the directions on the package.", 
                "Drain the pasta into the colander containing the beans, so the hot pasta water will warm the beans.",
                "Return drained pasta and beans to the pasta pot.",
                "When the tomatoes are done, pick out the garlic cloves, squeeze the garlic out of the skin into a small bowl and mash with a fork.",
                "Pour the roasted tomatoes into the pasta pot, add the garlic, the remaining 1 tablespoon of olive oil, the basil and additional salt and pepper, to taste.",
                "Toss to combine.",
                "Serve topped with the Parmesan." ],
        img: "img/gallery/vegie_pasta.jpg",
        calo: 592,
        nutri: "Energy: 592kcal, Fat: 27g, Cabohydrate: 62g, Protein: 17g, Sugar: 2g"},

        {id: 5,
        title: "Half-fired Beef Meatballs",
        intro: "Using olive oil instead and only small amount for seasoning to keep the orignal flavour.",
        ingr_search:["beef", "onion","cheese","parmesan cheese","garlic","ketchup","parsley","pepper"],
        ingr: ["1 pound lean ground beef",
                "1/2 cup onion finely chopped",
                "1/4 cup dried bread crumbs",
                "2 garlic cloves minced",
                "1 egg",
                "1/4 cup parmesan cheese finely grated",
                "3 table spoon ketchup",
                "1 teaspoon salt",
                "1/4 teaspoon pepper",
                "1 table spoon parsley minced (or about 1/2 table spoon dried)",],
        instr: ["Preheat oven to 400ºF. Spray a large cookie sheet with cooking spray.",
                "Mix together onion, bread crumbs, garlic, egg, cheese, ketchup, salt, pepper and parsley in a large mixing bowl.",
                "Add in ground beef and mix gently until combined. Do not overwork.", 
                "Form into 1-inch balls and place on prepared cookie sheet.",
                "Bake in preheated oven for 15-20 minutes, or until meatballs are browned and cooked through"],
        img: "img/gallery/beef_ball.jpg",
        calo: 400,
        nutri: "Energy: 400kcal, Fat: 17g, Cabohydrate: 16g, Protein: 30g, Sugar: 0.5g"},

        {id: 6,
        title: "Fruit Toast with Zero Calorie Syrup",
        intro: "A simple breakfast that easy to make when you have a busy day.",
        ingr_search:["bread", "fruit","syrup","banana","strawberry","apple","blueberry","zero calorie syrup","zero-calorie syrup","butter"],
        ingr: ["2-3 Slices of bread", 
                "Fruit of your choice, can be banana, strawberry, apple, blueberry...", 
                "3 teaspoon zero-calorie syrup",
                "1 teaspoon butter"],
        instr: ["If you use a toaster, thing will be pretty simple.",
                "Otherwise, put butter in a pan and heat it until butter is melt.",
                "Place the bread on the pan and wait until one side is crispy then change to the other side.",
                "Spread on a thin layer of cream cheese.", 
                "Put your fruit and syrup on the top."],
        img: "img/gallery/fruit_toast.jpg",
        calo: 172,
        nutri: "Energy: 172kcal, Fat: 10g, Cabohydrate: 13g, Protein: 7g, Sugar: 5g"},

        {id: 7,
        title: "Fruit Salad with Parmesan Chese",
        intro: "Refill the freshness inside you with a bowl of delicious salad.",
        ingr_search:["fruit", "yogurt","honey","banana","orange","mango","apple","strawberry","clementine","tangerine","yogurt"],
        ingr: ["1 cup plain yogurt",
        "1/4 cup honey",
        "1/2 teaspoon yogurt",
        "1 orange",
        "1 cup fresh strawberries cut in half",
        "2 clementines or tangerines sliced",
        "1 mango sliced",
        "1 apple sliced",
        "1 banana sliced"],
        instr: ["Slice your fruit in thinslices.", 
                "Sepreate segments of clementines.", 
                "Juice the orange.",
                "Making the sauce: combine the yogurt, honey in a small bowl then mix them well and set aside.",
                "Combine the fresh orange juice with all the fresh fruit.",
                "Top with honey yogurt sauce."],
        img: "img/gallery/fruit_salad.jpg",
        calo: 250,
        nutri: "Energy: 250kcal, Fat: 2.7g, Cabohydrate: 57.4g, Protein: 4.2g, Sugar: 0g"},

        {id: 8,
        title: "Chicken Breast Dumpling",
        intro: "Chicken breast is low in fat and a good source of protein.",
        ingr_search:["chicken", "cabbage","scallians","ginger","cornstarch", "wrapper","shanghai style","circular"],
        ingr: ["10 ounces skinless chicken breast, ﬁnely chopped",
                "6 ounces medium yellow Napa cabbage (approximately ⅕ cabbage), shredded",
                "2 slices fresh ginger, ⅛ to ¼ inch thick, diced",
                "2 scallions, finely chopped",
                "1 teaspoon salt",
                "1½ teaspoons sugar",
                "1 tablespoon chicken powder",
                "2 scallions, finely chopped",
                "1 teaspoon salt",
                "1½ teaspoons sugar",
                "1 tablespoon chicken powder",
                "1/4 teaspoon ground white pepper",
                "1 teaspoon cornstarch",
                " 1 teaspoon toasted sesame oil",
                "20 Shanghai-style circular wrappers",
                "1/4 teaspoon ground white pepper",
                "1 teaspoon cornstarch",
                "1 teaspoon toasted sesame oil",
                "20 Shanghai-style circular wrappers"],
        instr: ["In a large bowl, mix together the chicken, cabbage, ginger, and scallions until the mixture resembles a fine paste. Add the salt, sugar, chicken powder, white pepper, cornstarch, and toasted sesame oil and continue to stir for 3 to 5 minutes, until well incorporated.", 
                "Dampen a towel under which to keep the rest of the dumpling wrappers while you work.", 
                "Prepare a parchment-lined baking sheet on which to store the already prepared dumplings.",
                "Place 1½ teaspoons of filling in the center of each dumpling wrapper. Fold the dumpling into a half-moon shape. Hold the dumpling, seam-side up, between your thumb and index finger. Use the index finger and thumb of your other hand to pinch a section of the dumpling edge and pull it toward the web of the holding hand to make a small pleat. Repeat around the edge of the dumpling until you have between 6 and 8 pleats.",
                "Steam the dumpling and serve"],
        img: "img/gallery/chicken_dumpling.jpg",
        calo: 190,
        nutri: "Energy: 190kcal, Fat: 2.1g, Cabohydrate: 24.2g, Protein: 17.8g, Sugar: 0g"},
        
        //recorect still need intro =))))

        {id: 9,
        title: "Tamarind Prawn Curry",
        intro: "A healthier and simplified version of a popular Thai dish. This will probably become a family favourite dish.",
        ingr_search:["curry", "shrimp","prawn","curry","tomato","cherry tomato","tumeric","cumin","coriander"],
        ingr: ["1 tablespoon vegetable oil",
                "1 onion, chopped",
                "1 red chilli, finely chopped",
                "2 garlic cloves, crushed",
                "1 tablespoon grated ginger",
                "1 teaspoon turmeric",
                "1 teaspoon cumin seeds",
                "1 teaspoon ground coriander",
                "400g can cherry tomatoes",
                "1-2 tablespoons tamarind paste",
                "250g raw king prawns",
                "250g cooked basmati rice",
                "handful of coriander leaves, to serve"],
        instr: ["Heat the oil in a frying pan over a medium heat and cook the onion for 5-8 minutes until light golden.",
                "Stir in the chilli, garlic and ginger, and fry for another minute before adding the spices.",
                "Tip in the cherry tomatoes, swirl the can out with a splash of water and stir that into the pan as well.", 
                "Simmer for 5 minutes until the tomatoes burst and the sauce thickens.",
                "Stir in the tamarind and prawns, and simmer for 2-3 minutes until the prawns are cooked.",
                "Serve the curry on top of the rice, with the coriander scattered over."],
        img: "img/gallery/thai_curry.jpg",
        calo: 403,
        nutri: "Energy: 403kcal, Fat: 9g, Cabohydrate: 56g, Protein: 21g, Sugar: 0g"},

        {id: 10,
        title: "Salmon Salad with Sesame Dressing",
        intro: "Get three of your 5-a-day, plus healthy omega-3 fatty acids, vitamin C, folate and fibre in this quick, easy and low-calorie salad",
        ingr_search:["potato", "salad", "beans", "salmon", "green beans", "salad leaves", "semame", "onion", "tatami", "lemon"],
        ingr: [    "250g new potatoes, sliced",
                        "160g green beans, trimmed",
                        "2salmon fillets",
                        "80g salad leaves",
                        "4 small clementines, 3 sliced, 1 juiced",
                        "handful of basil, chopped",
                        "handful of coriander, chopped",
                        "2 teaspoons sesame oil",
                        "2 teaspoons tamari",
                        "½ lemon, juiced",
                        "1 red chilli, deseeded and chopped",
                        "2 tablespoons finely chopped onion"],
        instr: ["Steam the potatoes and beans in a steamer basket set over a pan of boiling water for 8 minutes. ",
                "Arrange the salmon fillets on top and steam for a further 6-8 minutes, or until the salmon flakes easily when tested with a fork.",
                "Meanwhile, mix the sesame oil, tamari, lemon juice, red chili, onion together along with the clementine juice.",
                "Arrange the salmon fillets on top, scatter over the herbs and spoon over the dressing." ],
        img: "img/gallery/salmon_salad.jpg",
        calo: 478,
        nutri: "Energy: 478kcal, Fat: 22g, Cabohydrate: 35g, Protein: 30g, Sugar: 0g"},

        {id: 11,
        title: "Cinnamon-Roll Overnight Oats",
        intro: "Easy, grab-and-go healthy breakfast",
        ingr_search:["oat", "almond", "almond_milk"],
        ingr: [    "2½ cups old-fashioned rolled oats",
                        "2½ cups unsweetened almond milk",
                        "6 teaspoons light brown sugar",
                        "1½ teaspoons vanilla extract",
                        "1¼ teaspoons ground cinnamon",
                        "½ teaspoon salt "],
        instr: ["Stir oats, milk, brown sugar, vanilla, cinnamon and salt together in a large bowl.",
                "Divide among five 8-ounce jars.",
                "Screw on lids and refrigerate overnight or for up to 5 days."],
        img: "img/gallery/oats.jpg",
        calo: 191,
        nutri: "Energy: 191kcal, Fat: 4g, Cabohydrate: 32g, Protein: 6g, Sugar: 4g"},

        {id: 12,
        title: "Avocado & Strawberry Smoothie",
        intro: "A creamy breakfast-friendly blend that's high in calcium and low in calories.",
        ingr_search:["avocado","strawberry","milk","lime","yogurt","honey"],
        ingr: ["1/2 avocado, stoned, peeled and cut into chunks",
                "150g strawberry, halved",
                "4 tablespoons low-fat natural yogurt",
                "200ml milk",
                "lime juice, to taste",
                "honey, to taste"],
        instr: ["Put all the ingredients in a blender and blend until smooth."],
        img: "img/gallery/straw_smoo.jpg",
        calo: 197,
        nutri: "Energy: 197kcal, Fat: 11g, Cabohydrate: 15g, Protein: 9g, Sugar: 0g"},

                {id: 11,
        title: "Cinnamon-Roll Overnight Oats",
        intro: "Easy, grab-and-go healthy breakfast",
        ingr_search:["oat", "almond", "almond_milk"],
        ingr: [    "2½ cups old-fashioned rolled oats",
                        "2½ cups unsweetened almond milk",
                        "6 teaspoons light brown sugar",
                        "1½ teaspoons vanilla extract",
                        "1¼ teaspoons ground cinnamon",
                        "½ teaspoon salt "],
        instr: ["Stir oats, milk, brown sugar, vanilla, cinnamon and salt together in a large bowl.",
                "Divide among five 8-ounce jars.",
                "Screw on lids and refrigerate overnight or for up to 5 days."],
        img: "img/gallery/oats.jpg",
        calo: 191,
        nutri: "Energy: 191kcal, Fat: 4g, Cabohydrate: 32g, Protein: 6g, Sugar: 4g"},

        {id: 12,
        title: "Avocado & Strawberry Smoothie",
        intro: "A creamy breakfast-friendly blend that's high in calcium and low in calories.",
        ingr_search:["avocado","strawberry","milk","lime","yogurt","honey"],
        ingr: ["1/2 avocado, stoned, peeled and cut into chunks",
                "150g strawberry, halved",
                "4 tablespoons low-fat natural yogurt",
                "200ml milk",
                "lime juice, to taste",
                "honey, to taste"],
        instr: ["Put all the ingredients in a blender and blend until smooth."],
        img: "img/gallery/straw_smoo.jpg",
        calo: 197,
        nutri: "Energy: 197kcal, Fat: 11g, Cabohydrate: 15g, Protein: 9g, Sugar: 0g"},

        {id: 13,
        title: "Strawberry Frozen Yogurt",
        intro: "Our easy strawberry frozen yogurt is intensely fruity and really creamy, perfect for a simple summer sweet treat while still being healthy.",
        ingr_search:["strawberry", "yogurt", "frozen"],
        ingr: [    "140g strawberries",
                   "½ x 405g can light condensed milk",
                   "500g tub 0%-fat Greek yogurt"],
        instr: ["Roughly chop half the strawberries and blend the rest in a blender to a purée.",
                "In a big bowl, stir the condensed milk into the puréed strawberries then gently stir in the yogurt until well mixed. Fold through the chopped strawberries.",
                "Scrape the mixture into a loaf tin or container, pop on the lid or wrap well in cling film and freeze overnight, until solid.",
                "Remove from the freezer about 10-15 minutes before you want to serve the frozen yogurt. Can be frozen for up to 1 month."],
        img: "img/gallery/frozen_straw.jpg",
        calo: 191,
        nutri: "Energy: 191kcal, Fat: 4g, Cabohydrate: 32g, Protein: 6g, Sugar: 4g"},

        {id: 14,
        title: "Spiced Roasted Apples & Blackberries",
        intro: "This guilt-free pudding tastes wonderful served with low-fat fromage frais, mixed with a little honey.",
        ingr_search:["avocado","strawberry","milk","lime","yogurt","honey"],
        ingr: [ "4 medium apples",
                "4 teaspoon clear honey",
                "½ teaspoon ground cinnamon",
                "Finely grated zest and juice of 1 large orange",
                "250g blackberry"],
        instr: ["Preheat the oven to 180C/gas 4/fan 160C.",
                "Core the apples so you have a hole the size of a pound coin in each one.",
                "Make a cut just into the skin around the middle of each apple.",
                "Stand the apples in a shallow baking dish large enough to take all four.",
                "Mix together the honey, cinnamon and orange zest, put an equal amount into the cavity of each apple,",
                "Pour the orange juice into the dish",
                "Roast the apples for about 40 minutes, spooning the juices over them occasionally.", 
                "Then, when the apples are almost ready, spoon the blackberries around and over the top of each apple.",
                " Return to the oven for 10 minutes or until the juices start to run. Spoon the blackberries and juices over the apples to serve."],
        img: "img/gallery/apple_blackberry.png",
        calo: 129,
        nutri: "Energy: 129kcal, Fat: 0.3g, Cabohydrate: 32g, Protein: 1g, Sugar: 15g"},

        {id: 15,
        title: "Chia & Coconut Pudding",
        intro: "Indulge in a taste of tropical paradise with this mouth-watering coconuty dessert containing healthy chia seeds.",
        ingr_search:["chia","coconut","honey","blueberry","yogurt","honey"],
        ingr: [ "400g can organic lite coconut cream",
                "80ml (1/3 cup)honey",
                "1/3 cup Chia Seeds",
                "Blueberries, to serve",
                "Toasted coconut, to serve"],
        instr: ["Place coconut cream, honey and Bioglan SuperFoods Chia Seeds in a bowl. Stir well to combine.",
                "Cover and store in the fridge for 4 hours or overnight to thicken.",
                "Divide among serving glasses. Top with berries, and coconut."],
        img: "img/gallery/chia_coco.jpg",
        calo: 220,
        nutri: "Energy: 220kcal, Fat: 9g, Cabohydrate: 22g, Protein: 13g, Sugar: 12g"},

        {id: 16,
        title: "Chocolate & Berry Mousse Pots",
        intro: "Dessert doesn't have to be devilish as this good-for-you pud proves.",
        ingr_search:["chocolate","berries","yogurt"],
        ingr: [ "75g dark chocolate 70% grated",
                "4 tbsp low-fat yogurt,",
                "2 large egg whites",
                "2 tsp caster sugar",
                "350g berries (try blueberries, raspberries, cherries or a mix)"],
        instr: ["Melt the chocolate in a heatproof bowl over a pan of simmering water, making sure the bowl doesn’t directly touch the water.",
                "Once melted, allow it to cool for 5-10 minutes, then stir in the yogurt",
                "Whisk the egg whites until stiff, then whisk in the sugar and beat until stiff again.",
                "Fold the whites into the chocolate mix – loosen the mixture first with a spoonful of egg white, then carefully fold in the rest, keeping as much air as possible.",
                "Put berries into small glasses or ramekins, then divide mousse on top. Chill in the fridge until set."],
        img: "img/gallery/choco_mousse.jpg",
        calo: 159,
        nutri: "Energy: 159kcal, Fat: 0.8g, Cabohydrate: 19g, Protein: 5g, Sugar: 15g"},

        {id: 17,
        title: "Stir-fried Chicken with Broccoli & Brown rice",
        intro: "Combine lean chicken with super-healthy broccoli, ginger and garlic for a quick and cheap, weeknight dinner.",
        ingr_search:["rice","brown rice","chicken", "chicken breast","onion","red pepper"],
        ingr: [ "200g trimmed broccoli florets (about 6), halved",
                "1 chicken breast (approx 180g), diced",
                "15g ginger, cut into shreds",
                "2 garlic cloves, cut into shreds",
                "1 red onion, sliced",
                "1 red pepper cut into cubes",
                "2 teaspoons vegetable oil",
                "1 teaspoons mild chilli powder",
                "1 tablespoon reduced-salt soy sauce",
                "1 tablespoon honey",
                "250g brown rice",
                "385mm of water "],
        instr: ["Wash the rice with water until the water is clear, then pour the rice with 385mm of water on to a rice cooker and cook until the rice cooker is ready",
                "Boil the broccoli for 4 minutes, and then drain the broccoli and reserve the water.",
                "Heat the vegetable oil in a non-stick frying pan or wok and stir-fry the ginger, garlic and onion for 2 minutes, add the mild chilli powder and stir briefly. ",
                "Add the chicken and stir-fry for 2 minutes more",
                "Tip the broccoli into the wok with the soy, honey, red pepper and 4 tbsp broccoli water then cook until heated through.",
                "Serve with cooked rice"],
        img: "img/gallery/brown_rice.jpg",
        calo: 448,
        nutri: "Energy:448kcal, Fat:9g, Cabohydrate:56g, Protein:33g, Sugar:15g"},

        {id: 18,
        title: "Chicken Satay Salad",
        intro: "Try this no-fuss, midweek meal that's high in protein and big on flavour. Marinate chicken breasts, then drizzle with a punchy peanut satay sauce.",
        ingr_search:["tamari","chicken","chicken breast","honey","lime","momegranate","lettuce","shallot","peanut","peanut butter"],
        ingr: [ "1 tablespoon tamari",
                "1 teaspoon medium curry powder",
                "¼ teaspoon ground cumin",
                "1 garlic clove, finely grated",
                "1 teaspoon clear honey",
                "2 skinless chicken breast fillets (or use turkey breast)",
                "1 tablespoon crunchy peanut butter (choose a sugar-free version with no palm oil, if possible)",
                "1 tablespoon sweet chilli sauce",
                "1 tbsp lime juice",
                "sunflower oil, for wiping the pan",
                "2 small lettuce bulb, cut into wedges",
                "¼ cucumber, halved and sliced",
                "1 shallot, halved and thinly sliced",
                "coriander, chopped",
                "seeds from ½ pomegranate"],
        instr: ["Pour the tamari into a large dish and stir in the curry powder, cumin, garlic and honey.",
                "Mix well.",
                "Slice the chicken breasts in half horizontally to make 4 fillets in total, then add to the marinade and mix well to coat. ",
                "Set aside in the fridge for at least 1 hr, or overnight, to allow the flavours to penetrate the chicken.",
                "Meanwhile, mix the peanut butter with the chilli sauce, lime juice, and 1 tbsp water to make a spoonable sauce.",
                "When ready to cook the chicken, wipe a large non-stick frying pan with a little oil. ",
                "Add the chicken and cook, covered with a lid, for 5-6 minutes on a medium heat, turning the fillets over for the last min, until cooked but still moist. ",
                "Set aside, covered, to rest for a few minutes.",
                "While the chicken rests, toss the lettuce wedges with the cucumber, shallot, coriander and pomegranate, and pile onto plates.",
                "Spoon over a little sauce.",
                "Slice the chicken, pile on top of the salad and spoon over the remaining sauce. Eat while the chicken is still warm."],
        img: "img/gallery/satay.jpg",
        calo: 353,
        nutri: "Energy: 353kcal, Fat: 10g, Cabohydrate: 24g, Protein: 38g, Sugar: 10g"},

        {id: 19,
        title: "Chicken & Lemon Skewers",
        intro: "These chicken skewers with a herby yogurt coating, salad and flatbreads taste great and they're good for you. Enjoy for a light weeknight dinner.",
        ingr_search:["chicken","lemon","yogurt","cumin","coriander","ginger","red onion"],
        ingr: [ "1 small pack mint, leaves picked",
                "150g natural yogurt, plus extra to serve (optional)",
                "1 lemon, zested and juiced",
                "½ teaspoon ground cumin",
                "½ teaspoon ground coriander",
                "2cm piece ginger, grated",
                "4 skinless chicken breasts, each cut into 6 pieces",
                "4 wholemeal flatbreads or pittas",
                "2 small lettuces bulb, sliced",
                "1 small red onion, sliced, to serve",
                "4 wooden skewers"
        ],
        instr: ["Chop half the mint and put in a bowl with the yogurt, half the lemon juice, all the lemon zest, spices and ginger.",
                "Mix well and season with lots of black pepper and a pinch of salt.",
                "Add the chicken pieces, mix well and put in the fridge for 20-30 minutes.",
                "Meanwhile, soak 4 large wooden skewers in water for at least 20 minutes.",
                "When you’re ready to cook the chicken, heat your grill to a medium heat and line the grill tray with foil. ",
                "Thread the chicken onto the soaked wooden or metal skewers and grill for 15-20 mins, turning halfway through, until browned and cooked through.",
                "Warm the flatbreads under the grill for a couple of seconds, then serve them topped with the lettuce, chicken, red onion, remaining lemon juice and mint, and any optional extras such as extra yogurt or pickled cabbage, chilli sauce and hummus.",],
        img: "img/gallery/chicken_skewers.jpg",
        calo: 159,
        nutri: "Energy: 159kcal, Fat: 10g, Cabohydrate: 25g, Protein: 33g, Sugar: 2g"},

        {id: 20,
        title: "Summer Chicken Stew",
        intro: "One-pots aren't just for winter, try this fresh summer version with leeks, green beans, peas, new potatoes and tender chicken thighs.",
        ingr_search:["chicken","chicken thight","chicken stock","leeks","green beans"],
        ingr: [ "2 tablespoons olive oil",
                "500g leeks, finely sliced",
                "2 big garlic cloves, finely sliced",
                "2 thyme sprigs, leaves picked or a 2 tablespoon dried thyme",
                "8 chicken thighs, skinless and boneless",
                "500g new potatoes, larger ones quartered, smaller ones halved",
                "350ml chicken stock",
                "200g green beans",
                "350g frozen peas",
                "lemon wedges, to serve",],
        instr: ["Heat the oil in a large casserole dish over a medium heat.",
                "Add the leeks, garlic and thyme, cover and cook gently for 10 mins, stirring occasionally.",
                "Season the chicken and tip into the dish with the potatoes.",
                "Turn up the heat, pour in the stock and bring to a simmer. ",
                "Reduce the heat and allow to gently bubble with the lid on for 35 mins. ",
                "Add the green beans and peas for the final 10 mins of cooking. Season to taste, then ladle into bowls or lipped plates with a squeeze of lemon.",],
        img: "img/gallery/chicken_stew.jpg",
        calo: 436,
        nutri: "Energy: 436kcal, Fat: 15g, Cabohydrate: 33g, Protein: 36g, Sugar: 0g"},

        {id: 21,
        title:"Slow Cooker Rice Pudding",
        intro:"Enjoy a nostalgic pudding, or a gluten-free alternative to porridge for breakfast. Add natural sweetness with fruit or almonds and a dusting of cinnamon.",
        ingr_search:[" butter", "semi-skimmed milk", "wholegrain rice", "nutmeg or cinnamon", " honey,", " toasted, flaked almonds and fruit", ],
        ingr:[
                "1 teaspoon of  butter",
                "1 L of semi-skimmed milk",
                "200g of wholegrain rice",
                "a touch of nutmeg or cinnamon",
                "1 tablespoon of  honey,",
                "a handful of  toasted, flaked almonds and fruit",
        ],
        instr:[
                "Butter the slow cooker all over the base and half way up the sides. Heat the milk to simmering point.",
                "Mix the pudding rice with the milk and pour it into the slow cooker.",
                "Add a touch of nutmeg or cinnamon. Cook for 2½ hours on High and stir once or twice if you can.",
                "Serve with honey, or flaked almonds and fruit if you like.",
        ],
        img:"img/gallery/rice_pudding.jpg",
        calo:200,
        nutri:"Energy:200kcal, Fat:4g, Cabohydrate:32g, Protein:8g, Sugar:8g"},

        {id: 22,
        title:"Chocolate Mousse",
        intro:"This sophisticated dessert is great for a dinner party, or for a lighter family pud use ordinary dark chocolate with less cocoa solids.",
        ingr_search:["chocolate", "powder", "coffee", " vanilla", "egg", "sugar", "yogurt", "raspberries"],
        ingr:[
                "85g of dark chocolate",
                "1 tablespoon of cocoa powder",
                "½ teaspoon of coffee granules",
                "½ teaspoon of vanilla extract",
                "2 egg whites",
                "1 tablespoon of golden caster sugar",
                "50g of full-fat Greek yogurt",
                "handful of raspberries",
        ],
        instr:[
                "Chop the chocolate very finely and put it into a large bowl that will fit over a pan of simmering water.",
                "Mix the cocoa, coffee and vanilla with 2 tbsp cold water, and pour over the chocolate.",
                "Place the bowl over the gently simmering water, give it all a stir, then remove from the heat.",
                "Leave with the bowl of chocolate still over the water, stirring occasionally to check when melted.",
                "Stir the melted chocolate, it will be quite thick. Stir in 2 tbsp boiling water and the chocolate will immediately thin down and become silky smooth.",
                "Leave to cool slightly.",
                "",
                "Whisk the egg whites to fairly soft peaks, then whisk in the sugar until thick and glossy.",
                "Beat the yogurt into the cooled chocolate. Fold about one-third of the egg whites into the chocolate mix using a large metal spoon, then very gently fold in the rest of the whites until they are evenly mixed in – being careful not to over-mix or you will lose the volume of the mousse.",
                "Spoon into 4 small cups or (125-150ml) ramekins and chill for a couple of hours, or overnight.",
        ],
        img:"img/gallery/choco_cake.jpg",
        calo:167,
        nutri:"Energy:167kcal, Fat:10g, Cabohydrate:15g, Protein:4g, Sugar:11g"},

        {id: 23,
        title:"Chocolate-dipped Strawberries",
        intro:"Indulge in chocolate-dipped strawberries for dessert or as part of a romantic picnic. Drizzle over milk and white chocolate for the wow factor.",
        ingr_search:["chocolate", " strawberries"],
        ingr:[
                "100g of dark chocolate",
                "400g of strawberries",
                "30g of white and milk chocolate",
        ],
        instr:[
                "Roughly chop the dark chocolate.",
                "Cut a strip of baking parchment and leave to one side.",
                "To melt the dark chocolate, fill a small pan with 2cm water and bring to a simmer. Put the chocolate in a heatproof bowl and rest it on top of the pan, ensuring the bowl isn’t touching the water. Stir the chocolate to gradually melt it. Or, melt the chocolate in 20 second blasts in the microwave, stirring after each blast until melted.",
                "Put the melted chocolate in a small deep bowl.",
                "Gently hold the strawberries by the leafy top and dip into the chocolate. Tap off any excess chocolate and put on the parchment to set. If you have any leftover chocolate, pour it onto another strip of parchment and leave it to set, it can be used again.",
                "If you'd like to decorate the strawberries, melt the white and milk chocolate and drizzle lightly over the fruit.",
        ],
        img:"img/gallery/choco_straw.jpg",
        calo:145,
        nutri:"Energy:145kcal, Fat:9g, Cabohydrate:12g, Protein:2g, Sugar:9g"},

        {id: 24,
        title:"Effortless Raspberry Iced Mousse",
        intro:"Use raspberries straight from the freezer for a mousse that will unfreeze your tastebuds.",
        ingr_search:["cream cheese","lemon", "raspberries"],
        ingr:[
                "500g of low-fat cream cheese",
                "50g of icing sugar",
                "squeeze or two of lemon juice",
                "250g of frozen raspberries",
        ],
        instr:[
                "Tip the quark and sugar into a large bowl, squeeze in a few drops of lemon juice and beat with a wooden spoon until smooth and creamy (you can do this an hour or two ahead).",
                "Gently stir in raspberries until they begin to break up and mixture is streaked pink; taste and add a little more lemon juice if liked. Spoon into glasses and serve.",
        ],
        img:"img/gallery/raspberry.jpg",
        calo:158,
        nutri:"Energy:158kcal, Fat:0g, Cabohydrate:21g, Protein:19g, Sugar:13g"},

        {id: 25,
        title:"Easy Thai Beef Salad",
        intro:"This substantial salad is packed full of filling and flavour-packed ingredients, yet it's low-fat and good for you.",
        ingr_search:["beef",, "lime", "chili", "leaf salad", "beansprouts", "grapes", ],
        ingr:[
                "300g of beef steak",
                "2 teaspons of oil",
                "1 lime",
                "1 chili",
                "1 tablespoon of light brown soft sugar",
                "85g of leaf salad",
                "140g of beansprouts",
                "140g of red grapes",
        ],
        instr:[
                "Juice the lime",
                "De-seed the chili and slice",
                "Rub the steak with 1 tsp oil and season.",
                "Fry in a hot pan for 2-2½ mins each side (depending on thickness), for medium rare.",
                "Transfer to a plate, cover loosely with foil and rest for 5 mins.",
                "Make the dressing by mixing the lime juice, chilli, sugar and remaining oil in a bowl. Set aside until the sugar dissolves.",
                "Divide the salad leaves, beansprouts and grapes between 2 serving bowls.",
                "Thinly slice the steak and add the juices to the dressing.",
                "Drizzle this over the salads, toss with the sliced beef and serve immediately with rice, if you like.",
        ],
        img:"img/gallery/thai_beef.jpg",
        calo:317,
        nutri:"Energy:317kcal, Fat:11g, Cabohydrate:21g, Protein:36g, Sugar:0g"},

        {id: 26,
        title:"Quick Beef & Broccoli One-pot",
        intro:"Create a delicious beef and broccoli meal in one pot, fast!",
        ingr_search:["cashew nuts", "beef", "broccoli", "celery", "beef stock", "horseradish", "cheese", ],
        ingr:[
                "1 tablespoon of olive oil",
                "50g of cashew nuts",
                "400g of frying beef steak",
                "1 large head broccoli",
                "4 celery stick",
                "150ml of beef stock",
                "2tbsp of horseradish sauce",
                "2tbsp of low-fat fromage frais",
        ],
        instr:[
                "Slice the celery",
                "Cut the beef into strips",
                "Broke the broccoli into florets",
                "Juice the lime",
                "Heat the oil in a frying pan, add the nuts and toss for a few secs until lightly toasted. Set aside.",
                "Season the steak strips with plenty of pepper and stir-fry over a high heat for 1-2 mins to brown. Set aside with the nuts.",
                "Tip the broccoli and celery into the pan and stir-fry for 2 mins.",
                "Pour the stock over, cover and simmer for 2 mins.",
                "Meanwhile, mix the horseradish and fromage frais together.",
                "Return the steak to the pan and toss with the veg, then sprinkle over the nuts and serve with the creamy horseradish. Great with mashed potatoes.",
        ],
        img:"img/gallery/one_beef.jpg",
        calo:269,
        nutri:"Energy:269kcal, Fat:14g, Cabohydrate:6g, Protein:29g, Sugar:4g"},
        
        {id: 27,
        title:"Healthy Beef Chow Mein",
        intro:"Swap your weekly takeaway for this healthy beef chow mein – it's quick to cook and low in fat and calories.",
        ingr_search:["noodle nests", "oil", "steak", "small", "ginger", "mushrooms", "garlic_cloves", "beansprouts", " tamari", "spring onions (65g)" ],
        ingr:[
                "85g of noodle nests",
                "2 teaspoons of oil",
                "200g of lean steak",
                "1 small",
                "15g of ginger",
                "160g of chestnut mushrooms",
                "2 garlic cloves",
                "160g of beansprouts",
                "1tsp of  tamari",
                "1tbsp of  brown rice vinegar",
                "65g of spring onions (65g), cut into diagonal lengths",
        ],
        instr:[
                "Cut the beef into strips",
                "chop the onion, ginger, garlic",
                "Slice the mushroom and onion",
                "Cook the noodles following pack instructions.",
                "Meanwhile, heat half the oil in a wok and stir-fry the beef over a high heat for 30 seconds until browned. Tip onto a plate, set aside, then add the remaining oil to the wok.",
                "Stir-fry the onion and ginger until softened.",
                "Add a drop of water to prevent burning, if needed and cook covered for 2-3 mins.",
                "Stir in the mushrooms and garlic, and fry until they start to soften (around 3 mins), then add the beansprouts and cook for a minute or two more until piping hot.",
                "Mix the tamari and vinegar together in a small bowl with 2 tbsp water.",
                "Add the drained noodles to the wok, toss well, then add the tamari mixture, spring onions and the beef.",
                "Stir-fry for a few minutes until heated through.",
                "Season with plenty of black pepper and serve.",
        ],
        img:"img/gallery/mein_beef.jpg",
        calo:407,
        nutri:"Energy:407kcal, Fat:11g, Cabohydrate:41g, Protein:32g, Sugar:0g"},

        {id: 28,
        title:"Beef Schnitzel",
        intro:"Tasty pan-fried beef recipe.",
        ingr_search:["steaks", "flour", " paprika", "eggs,", "breadcrumbs",],
        ingr:[
                "5 thin-cut_steaks",
                "50g of plain flour",
                "2 teaspoons of  paprika",
                "2 eggs,",
                "250g of dried breadcrumbs",
                "5 teaspoons of butter",
                "5 teaspoons of olive_oil",
        ],
        instr:[
                "Stretch a piece of cling film over a chopping board, lay the steaks on top of it, then put another piece of cling film on top.",
                "Use a rolling pin to bash the steaks until they are really flat and thin.",
                "Mix the flour and paprika with some salt and pepper on a plate.",
                "Lightly beat the egg on a dish.",
                "Put the egg and breadcrumbs on two more plates, then dip the steaks into the flour first, then the egg, then the breadcrumbs.",
                "Heat 1 tsp of butter and 1 tsp of oil in a large frying pan, then cook one of the schnitzels for about 1 min on each side until the breadcrumbs are golden and crispy.",
                "Repeat Step 3 for the other schnitzels.",
                "Serve with lemon wedges, salad and coleslaw, if you like.",
        ],
        img:"img/gallery/beef_schitzel.jpg",
        calo:468,
        nutri:"Energy:468kcal, Fat:14g, Cabohydrate:46g, Protein:43g, Sugar:3g"}
]

//no needs template because we can auto generate recipe from text